# Generated by Django 5.2.4 on 2025-07-08 16:25

import myapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=myapp.storage_backends.MinioStorage(), upload_to='avatars/'),
        ),
    ]
